import { Task, RandomEvent, Notification, LevelDefinition } from "./types";

export const LEVELS: LevelDefinition[] = [
  { level: 1, title: "Profesor Stagiar",      minXP: 0,    maxXP: 299,  badge: "🎓" },
  { level: 2, title: "Profesor Debut",         minXP: 300,  maxXP: 699,  badge: "📚" },
  { level: 3, title: "Profesor Titular",       minXP: 700,  maxXP: 1199, badge: "🏫" },
  { level: 4, title: "Profesor Experimentat",  minXP: 1200, maxXP: 1799, badge: "⭐" },
  { level: 5, title: "Profesor Senior",        minXP: 1800, maxXP: 2499, badge: "🏆" },
  { level: 6, title: "Profesor Mentor",        minXP: 2500, maxXP: 9999, badge: "👑" },
];

export const TASKS: Task[] = [
  {
    id: "t1",
    hour: 8,
    minute: 0,
    title: "Începerea zilei — lecția de istorie",
    type: "lesson",
    urgency: "medium",
    timeoutSeconds: 90,
    timeoutPenalty: 30,
    scenario: `Ora 08:00. Clasa a X-a B intră zgomotos. Ai pregătit o lecție despre Al Doilea Război Mondial, dar observi că 6 elevi nu au caietele, iar Andrei — elev cu note bune — doarme în bancă. Planul tău de lecție necesită 40 de minute, dar directoarea ți-a anunțat ieri că vine în inspecție undeva în cursul dimineții.`,
    choices: [
      {
        id: "t1c1",
        text: "Începi lecția direct, ignori dezordinea — acoperirea materiei e prioritatea.",
        xpReward: 40,
        skillEffects: { organizare: 5, empatie: -8, disciplina: -5 },
        immediateConsequence: "Lecția avansează, dar jumătate din clasă e pierdută. Andrei continuă să doarmă.",
        longTermConsequence: "Notele la test vor fi slabe. Directoarea observă lipsa de control la inspecție.",
        isOptimal: false,
      },
      {
        id: "t1c2",
        text: "Oprești clasa, stabilești regulile clar, trimiți după caiete, trezești Andrei discret.",
        xpReward: 85,
        skillEffects: { disciplina: 12, organizare: 8, empatie: 5 },
        immediateConsequence: "5 minute pierdute, dar clasa e atentă. Andrei e recunoscător că nu l-ai umilit.",
        longTermConsequence: "Clasa te respectă mai mult. Andrei vine cu teme mai des. Inspecția merge bine.",
        isOptimal: true,
      },
      {
        id: "t1c3",
        text: "Schimbi planul — faci o dezbatere orală, nu ai nevoie de caiete.",
        xpReward: 65,
        skillEffects: { rezilienta: 10, comunicare: 8, organizare: -5 },
        immediateConsequence: "Dezbaterea prinde bine. Câțiva elevi excelenți strălucesc.",
        longTermConsequence: "Materia nu e acoperită conform planului. Risc la inspecție.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t_innovation",
    hour: 9,
    minute: 30,
    title: "Lecția care nu merge",
    type: "lesson",
    urgency: "medium",
    timeoutSeconds: 75,
    timeoutPenalty: 35,
    scenario: `Ora 09:30. Ai pregătit o lecție despre Revoluția Franceză. Clasa a XI-a A e complet dezinteresată — telefoane pe bancă, priviri în gol. Un elev spune cu voce tare: "De ce contează asta pentru noi?" Alți câțiva râd. Ai 20 de minute rămase din oră și energia clasei e zero.`,
    choices: [
      {
        id: "t_inn_c1",
        text: "Continui lecția ca planificat — materia trebuie predată indiferent de reacție.",
        xpReward: 35,
        skillEffects: { organizare: 5, empatie: -10, comunicare: -5 },
        immediateConsequence: "Finalizezi lecția, dar jumătate din clasă nu a ascultat. Atmosfera e rece.",
        longTermConsequence: "Elevii te percep ca rigid. Participarea la ore scade săptămâna viitoare.",
        isOptimal: false,
      },
      {
        id: "t_inn_c2",
        text: "Oprești totul și întrebi clasa: 'Ce ar trebui să predau ca să fie relevant pentru voi?'",
        xpReward: 90,
        skillEffects: { empatie: 15, comunicare: 18, rezilienta: 8 },
        immediateConsequence: "Clasa e surprinsă. Câțiva elevi încep să vorbească serios. Improvizezi o dezbatere.",
        longTermConsequence: "Ora devine una dintre cele mai citate de elevi. Participarea crește cu 40%.",
        isOptimal: true,
      },
      {
        id: "t_inn_c3",
        text: "Dai un test neanunțat — atenția revine instant din frică.",
        xpReward: 45,
        skillEffects: { disciplina: 10, empatie: -12, comunicare: -5 },
        immediateConsequence: "Clasa se trezește, dar din teamă. Atmosfera devine tensionată.",
        longTermConsequence: "Elevii asociază ora ta cu stresul. Absenteismul crește ușor.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t2",
    hour: 10,
    minute: 0,
    title: "Conflict între elevi — situație escaladată",
    type: "conflict",
    urgency: "high",
    timeoutSeconds: 60,
    timeoutPenalty: 50,
    scenario: `Ora 10:00. În pauza mare, doi elevi — Radu și Victor — se ceartă violent în curtea școlii. Alți 15 elevi filmează cu telefonul. Radu l-a împins pe Victor; situația e pe cale să degenereze. Ești singurul profesor prezent. Ai 60 de secunde să acționezi înainte să intervină paza.`,
    choices: [
      {
        id: "t2c1",
        text: "Intervii fizic, îi desparți imediat, ridici vocea pentru autoritate.",
        xpReward: 55,
        skillEffects: { disciplina: 15, empatie: -10, rezilienta: 5 },
        immediateConsequence: "Conflictul se oprește, dar ești agresiv. Elevii te văd sever.",
        longTermConsequence: "Un părinte reclamă că ai 'intimidat' elevii. Dosar la secretariat.",
        isOptimal: false,
      },
      {
        id: "t2c2",
        text: "Îi separi calm, trimiți restul elevilor în clase, discuți cu fiecare separat.",
        xpReward: 90,
        skillEffects: { empatie: 15, comunicare: 12, disciplina: 8 },
        immediateConsequence: "Situația se dezamorsează. Elevii văd că ești echilibrat sub presiune.",
        longTermConsequence: "Radu și Victor vin la tine cu probleme în viitor. Reputație bună.",
        isOptimal: true,
      },
      {
        id: "t2c3",
        text: "Chemi paza și nu intervii direct — nu e responsabilitatea ta.",
        xpReward: 20,
        skillEffects: { disciplina: -15, empatie: -5, organizare: 3 },
        immediateConsequence: "Paza vine în 3 minute. Victor e lovit în acest timp. Incident înregistrat.",
        longTermConsequence: "Directoarea te întreabă de ce nu ai intervenit. Avertisment verbal.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t_favoritism",
    hour: 11,
    minute: 0,
    title: "Dilema notei",
    type: "parent",
    urgency: "high",
    timeoutSeconds: 60,
    timeoutPenalty: 50,
    scenario: `Ora 11:00. Maria — fata directorului — a luat 5 la testul de săptămâna trecută. Tatăl ei te oprește în cancelarie înainte de oră și sugerează calm, dar ferm: "Poate ar merita să reevaluezi lucrarea Mariei. E o fată serioasă." Ai lucrarea în față. Răspunsurile sunt greșite clar. Colegii de cancelarie aud discuția.`,
    choices: [
      {
        id: "t_fav_c1",
        text: "Îi explici politicos că nota reflectă exact lucrarea și nu o poți schimba.",
        xpReward: 95,
        skillEffects: { disciplina: 18, comunicare: 12, rezilienta: 10 },
        immediateConsequence: "Directorul pleacă tăcut. Colegii tăi te privesc cu respect.",
        longTermConsequence: "Reputația ta de profesor corect se consolidează. Maria învață că nota se merită.",
        isOptimal: true,
      },
      {
        id: "t_fav_c2",
        text: "Spui că 'vei reanalia' lucrarea și ridici nota la 7 pentru a evita conflictul.",
        xpReward: 20,
        skillEffects: { disciplina: -20, empatie: -5, rezilienta: -10 },
        immediateConsequence: "Directorul mulțumit pleacă. Colegii care au auzit tac, dar notează.",
        longTermConsequence: "Un coleg reclamă la Inspectorat. Audit al notelor tale. Stres major.",
        isOptimal: false,
      },
      {
        id: "t_fav_c3",
        text: "Propui o reexaminare orală oficială în fața unui alt profesor — transparent și corect.",
        xpReward: 75,
        skillEffects: { disciplina: 12, organizare: 10, comunicare: 8 },
        immediateConsequence: "Directorul acceptă surprins. Procedura e corectă și documentată.",
        longTermConsequence: "Maria pică și reexaminarea. Situația e clară. Directorul te respectă pe termen lung.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t3",
    hour: 13,
    minute: 0,
    title: "Întâlnire cu părintele — situație tensionată",
    type: "parent",
    urgency: "high",
    timeoutSeconds: 75,
    timeoutPenalty: 45,
    scenario: `Ora 13:00. Doamna Ionescu — mama Elenei — a venit neanunțată. Elena a luat 4 la ultimul test, deși mama e convinsă că fata știe materia perfect. Tonul doamnei e agresiv de la început: "Ați greșit la corectare!" Ai documentele de față, dar și o clasă care te așteaptă la 13:15.`,
    choices: [
      {
        id: "t3c1",
        text: "Îi explici calm și detaliat fiecare răspuns greșit al Elenei, cu dovezi.",
        xpReward: 80,
        skillEffects: { comunicare: 15, empatie: 8, organizare: 10 },
        immediateConsequence: "Mama se calmează. Recunoaște că Elena a mai zis că nu a pregătit tema.",
        longTermConsequence: "Elena vine la consultații. Nota crește la semestrul următor.",
        isOptimal: true,
      },
      {
        id: "t3c2",
        text: "Îi spui că nu poți discuta acum, programezi o întâlnire formală cu directoarea.",
        xpReward: 50,
        skillEffects: { organizare: 8, comunicare: -5, empatie: -8 },
        immediateConsequence: "Mama pleacă supărată. Zice că 'va rezolva altfel'.",
        longTermConsequence: "Plângere la Inspectorat. Audit al notelor tale. Stres ridicat.",
        isOptimal: false,
      },
      {
        id: "t3c3",
        text: "Oferi să refaci testul Elenei cu supraveghere strictă săptămâna viitoare.",
        xpReward: 65,
        skillEffects: { empatie: 10, rezilienta: 5, organizare: -5 },
        immediateConsequence: "Mama acceptă surprinsă. Tensiunea scade.",
        longTermConsequence: "Elena pică și retestul. Situația e mai clară acum, fără conflict.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t4",
    hour: 15,
    minute: 30,
    title: "Inspecția directoarei — lecție demonstrativă",
    type: "evaluation",
    urgency: "critical",
    timeoutSeconds: 45,
    timeoutPenalty: 70,
    scenario: `Ora 15:30. Directoarea intră fără să bată în ușă. Ai clasa a IX-a C — cea mai dificilă clasă. Trei elevi vorbesc. Planul tău de lecție e pe jumătate terminat. Pe tablă ai o diagramă incompletă. Directoarea se așează în spatele clasei și scoate un caiet de observații.`,
    choices: [
      {
        id: "t4c1",
        text: "Continui lecția ca și cum nu s-ar fi întâmplat nimic — nu schimbi nimic.",
        xpReward: 70,
        skillEffects: { rezilienta: 15, organizare: 5, comunicare: 5 },
        immediateConsequence: "Directoarea notează că ești natural și neafectat de presiune.",
        longTermConsequence: "Feedback pozitiv la raportul de inspecție. Recomandare pentru gradație.",
        isOptimal: true,
      },
      {
        id: "t4c2",
        text: "Îți schimbi complet abordarea — faci o lecție 'de show' improvizată.",
        xpReward: 45,
        skillEffects: { comunicare: 8, organizare: -10, rezilienta: 5 },
        immediateConsequence: "Lecția pare artificială. Directoarea observă că nu urmezi planul.",
        longTermConsequence: "Feedback mixt — creativitate da, consecvență nu.",
        isOptimal: false,
      },
      {
        id: "t4c3",
        text: "Implici directoarea — o inviti să interacționeze cu elevii ca 'invitat special'.",
        xpReward: 85,
        skillEffects: { comunicare: 18, empatie: 10, organizare: 5 },
        immediateConsequence: "Directoarea e plăcut surprinsă. Elevii sunt mai atenți.",
        longTermConsequence: "Lecție menționată ca 'exemplu de bune practici' la consiliul profesoral.",
        isOptimal: true,
      },
    ],
  },
  {
    id: "t_burnout",
    hour: 16,
    minute: 30,
    title: "Limita ta personală",
    type: "admin",
    urgency: "high",
    timeoutSeconds: 80,
    timeoutPenalty: 30,
    scenario: `Ora 16:30. A 8-a oră din ziua ta. Ai dureri de cap. Un coleg te roagă să îi acoperi ora de mâine — "ultima oară, promit". Acasă te așteaptă 40 de lucrări de corectat. Telefonul sună: un părinte nervos vrea să vorbească acum. Ai energie pentru maximum 60 de minute de muncă.`,
    choices: [
      {
        id: "t_burn_c1",
        text: "Accepți tot: acoperit ora, răspuns telefon, corectezi lucrările până la 21:00.",
        xpReward: 30,
        skillEffects: { organizare: 5, rezilienta: -18, empatie: -8 },
        immediateConsequence: "Rezolvi totul, dar ești complet epuizat. Nu dormi bine.",
        longTermConsequence: "Burnout în 6 săptămâni. Calitatea lecțiilor scade vizibil.",
        isOptimal: false,
      },
      {
        id: "t_burn_c2",
        text: "Refuzi politicos ora colegului, amâni părintele pentru mâine dimineață, corectezi 10 lucrări și pleci.",
        xpReward: 90,
        skillEffects: { rezilienta: 18, organizare: 12, empatie: 8 },
        immediateConsequence: "Pleci la timp. Colega înțelege. Părintele acceptă întâlnirea de mâine.",
        longTermConsequence: "Sustenabilitate pe termen lung. Ești mai prezent și mai eficient zilnic.",
        isOptimal: true,
      },
      {
        id: "t_burn_c3",
        text: "Accepți ora colegului dar ignori telefonul și lucrările — 'mâine le rezolv pe toate'.",
        xpReward: 40,
        skillEffects: { rezilienta: -5, organizare: -12, empatie: -3 },
        immediateConsequence: "Pleci mai devreme, dar cu lista de probleme pentru mâine dublată.",
        longTermConsequence: "Restanțele se acumulează. Mâine e și mai greu.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t5",
    hour: 17,
    minute: 0,
    title: "Sfârșitul zilei — raport și epuizare",
    type: "admin",
    urgency: "medium",
    timeoutSeconds: 120,
    timeoutPenalty: 20,
    scenario: `Ora 17:00. Toate orele s-au terminat. Trebuie să completezi catalogul electronic, să răspunzi la 12 emailuri de la părinți, să pregătești lecția de mâine și să corectezi 22 de lucrări. Partenerul/a ți-a trimis mesaj: 'Vii acasă la timp azi?' Ai energie pentru aproximativ 90 de minute de muncă eficientă.`,
    choices: [
      {
        id: "t5c1",
        text: "Faci totul — rămâi până la 20:00, sacrifici seara personală.",
        xpReward: 55,
        skillEffects: { organizare: 15, rezilienta: -10, empatie: -5 },
        immediateConsequence: "Tot e rezolvat, dar ești epuizat. Partenerul/a e dezamăgit/ă.",
        longTermConsequence: "Burnout în 3 luni. Eficiența ta scade vizibil.",
        isOptimal: false,
      },
      {
        id: "t5c2",
        text: "Prioritizezi: catalogul + 3 emailuri urgente, restul mâine dimineață.",
        xpReward: 85,
        skillEffects: { organizare: 10, rezilienta: 12, empatie: 8 },
        immediateConsequence: "Pleci la timp. Te simți vinovat dar echilibrat.",
        longTermConsequence: "Sustenabilitate pe termen lung. Ești mai odihnit și mai eficient.",
        isOptimal: true,
      },
      {
        id: "t5c3",
        text: "Nu faci nimic extra — pleci imediat, 'mâine e o zi nouă'.",
        xpReward: 15,
        skillEffects: { organizare: -15, rezilienta: 3, empatie: 2 },
        immediateConsequence: "Pleci relaxat, dar catalogul necompletat generează email de la director.",
        longTermConsequence: "Reputație de neseriozitate. Colegii se plâng.",
        isOptimal: false,
      },
    ],
  },
];

export const EXPERT_CHOICES: Record<string, { choiceIndex: number; rationale: string }> = {
  t1:            { choiceIndex: 1, rationale: "Profesorii experimentați pierd 5 minute la start pentru a câștiga 40 de minute de atenție reală." },
  t_innovation:  { choiceIndex: 1, rationale: "Cel mai bun profesor nu e cel care predă — e cel care face clasa să vrea să înțeleagă." },
  t2:            { choiceIndex: 1, rationale: "Calm sub presiune = autoritate reală. Panica sau agresivitatea pierd respectul imediat." },
  t_favoritism:  { choiceIndex: 0, rationale: "Integritatea nu e negociabilă. Un profesor corect e mai valoros decât unul comod." },
  t3:            { choiceIndex: 0, rationale: "Dovezile clare și empatia împreună dezarmează orice părinte agresiv." },
  t4:            { choiceIndex: 2, rationale: "Implicarea directorului transformă o inspecție incomodă într-o demonstrație de leadership." },
  t_burnout:     { choiceIndex: 1, rationale: "Un profesor odihnit face mai mult în 60 de minute decât unul epuizat în 3 ore." },
  t5:            { choiceIndex: 1, rationale: "Sustenabilitatea e skill profesional, nu slăbiciune. Prioritizarea salvează cariera pe termen lung." },
};

export const RANDOM_EVENTS: RandomEvent[] = [
  {
    id: "re1",
    triggerAfterTask: "t1",
    probability: 0.4,
    title: "Elev cu criză de anxietate",
    description: "Maria iese brusc din clasă plângând. Colega ei îți spune în șoaptă că Maria are probleme acasă.",
    effect: { empatie: 10, organizare: -5 },
    xpEffect: 30,
    notification: "⚠️ Situație sensibilă: Maria are nevoie de ajutor imediat.",
  },
  {
    id: "re2",
    triggerAfterTask: "t2",
    probability: 0.35,
    title: "Telefon de la Inspectorat",
    description: "Inspectorul școlar anunță o vizită neplănuită pentru după-amiază.",
    effect: { rezilienta: -8, organizare: 5 },
    xpEffect: -20,
    notification: "📞 URGENT: Inspectoratul vine astăzi. Pregătește dosarul de inspecție!",
  },
  {
    id: "re3",
    triggerAfterTask: "t3",
    probability: 0.3,
    title: "Elev care copiază la test",
    description: "Surprinzi un elev cu fița sub bancă în timp ce supraveghezi testul.",
    effect: { disciplina: 10, empatie: -5 },
    xpEffect: 25,
    notification: "🚨 Incident: Copiat la test detectat. Cum procedezi?",
  },
];

export const SCHEDULED_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "warning",
    message: "📅 Peste 15 minute ai întâlnirea cu mama Elenei. Pregătește-ți documentele!",
    triggerBeforeTaskId: "t3",
    minutesBefore: 15,
    autoHideSeconds: 8,
  },
  {
    id: "n2",
    type: "urgent",
    message: "🚨 URGENT: Conflictul dintre Radu și Victor escaladează în curte. Acționează acum!",
    triggerBeforeTaskId: "t2",
    minutesBefore: 0,
    autoHideSeconds: 5,
  },
  {
    id: "n3",
    type: "consequence",
    message: "📉 Ai ignorat elevul deranjator de la ora 8. Acum toată clasa e neatentă.",
    triggerBeforeTaskId: "t4",
    minutesBefore: 30,
    autoHideSeconds: 8,
  },
  {
    id: "n4",
    type: "warning",
    message: "⏰ Directoarea face inspecții astăzi. Fii pregătit/ă în orice moment.",
    triggerBeforeTaskId: "t4",
    minutesBefore: 60,
    autoHideSeconds: 6,
  },
  {
    id: "n5",
    type: "achievement",
    message: "🌟 Ai gestionat excelent conflictul! +15 Empatie, +12 Comunicare",
    triggerBeforeTaskId: "t3",
    minutesBefore: -5,
    autoHideSeconds: 6,
  },
];
