import { Task, RandomEvent, Notification, LevelDefinition } from "./types";

export const LEVELS: LevelDefinition[] = [
  { level: 1, title: "Profesor Stagiar",      minXP: 0,    maxXP: 299,  badge: "🎓" },
  { level: 2, title: "Profesor Debut",         minXP: 300,  maxXP: 699,  badge: "📚" },
  { level: 3, title: "Profesor Titular",       minXP: 700,  maxXP: 1199, badge: "🏫" },
  { level: 4, title: "Profesor Experimentat",  minXP: 1200, maxXP: 1799, badge: "⭐" },
  { level: 5, title: "Profesor Senior",        minXP: 1800, maxXP: 2499, badge: "🏆" },
  { level: 6, title: "Profesor Mentor",        minXP: 2500, maxXP: 9999, badge: "👑" },
];

export const TASKS: Task[] = [
  {
    id: "t1",
    hour: 8,
    minute: 0,
    title: "Începerea zilei — lecția de istorie",
    type: "lesson",
    urgency: "medium",
    timeoutSeconds: 90,
    timeoutPenalty: 30,
    scenario: `Ora 08:00. Clasa a X-a B intră zgomotos. Ai pregătit o lecție despre Al Doilea Război Mondial, dar observi că 6 elevi nu au caietele, iar Andrei — elev cu note bune — doarme în bancă. Planul tău de lecție necesită 40 de minute, dar directoarea ți-a anunțat ieri că vine în inspecție undeva în cursul dimineții.`,
    choices: [
      {
        id: "t1c1",
        text: "Începi lecția direct, ignori dezordinea — acoperirea materiei e prioritatea.",
        xpReward: 40,
        skillEffects: { organizare: 5, empatie: -8, disciplina: -5 },
        immediateConsequence: "Lecția avansează, dar jumătate din clasă e pierdută. Andrei continuă să doarmă.",
        longTermConsequence: "Notele la test vor fi slabe. Directoarea observă lipsa de control la inspecție.",
        isOptimal: false,
      },
      {
        id: "t1c2",
        text: "Oprești clasa, stabilești regulile clar, trimiți după caiete, trezești Andrei discret.",
        xpReward: 85,
        skillEffects: { disciplina: 12, organizare: 8, empatie: 5 },
        immediateConsequence: "5 minute pierdute, dar clasa e atentă. Andrei e recunoscător că nu l-ai umilit.",
        longTermConsequence: "Clasa te respectă mai mult. Andrei vine cu teme mai des. Inspecția merge bine.",
        isOptimal: true,
      },
      {
        id: "t1c3",
        text: "Schimbi planul — faci o dezbatere orală, nu ai nevoie de caiete.",
        xpReward: 65,
        skillEffects: { rezilienta: 10, comunicare: 8, organizare: -5 },
        immediateConsequence: "Dezbaterea prinde bine. Câțiva elevi excelenți strălucesc.",
        longTermConsequence: "Materia nu e acoperită conform planului. Risc la inspecție.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t2",
    hour: 10,
    minute: 0,
    title: "Conflict între elevi — situație escaladată",
    type: "conflict",
    urgency: "high",
    timeoutSeconds: 60,
    timeoutPenalty: 50,
    scenario: `Ora 10:00. În pauza mare, doi elevi — Radu și Victor — se ceartă violent în curtea școlii. Alți 15 elevi filmează cu telefonul. Radu l-a împins pe Victor; situația e pe cale să degenereze. Ești singurul profesor prezent. Ai 60 de secunde să acționezi înainte să intervină paza.`,
    choices: [
      {
        id: "t2c1",
        text: "Intervii fizic, îi desparți imediat, ridici vocea pentru autoritate.",
        xpReward: 55,
        skillEffects: { disciplina: 15, empatie: -10, rezilienta: 5 },
        immediateConsequence: "Conflictul se oprește, dar ești agresiv. Elevii te văd sever.",
        longTermConsequence: "Un părinte reclamă că ai 'intimidat' elevii. Dosar la secretariat.",
        isOptimal: false,
      },
      {
        id: "t2c2",
        text: "Îi separi calm, trimiți restul elevilor în clase, discuți cu fiecare separat.",
        xpReward: 90,
        skillEffects: { empatie: 15, comunicare: 12, disciplina: 8 },
        immediateConsequence: "Situația se dezamorsează. Elevii văd că ești echilibrat sub presiune.",
        longTermConsequence: "Radu și Victor vin la tine cu probleme în viitor. Reputație bună.",
        isOptimal: true,
      },
      {
        id: "t2c3",
        text: "Chemi paza și nu intervii direct — nu e responsabilitatea ta.",
        xpReward: 20,
        skillEffects: { disciplina: -15, empatie: -5, organizare: 3 },
        immediateConsequence: "Paza vine în 3 minute. Victor e lovit în acest timp. Incident înregistrat.",
        longTermConsequence: "Directoarea te întreabă de ce nu ai intervenit. Avertisment verbal.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t3",
    hour: 13,
    minute: 0,
    title: "Întâlnire cu părintele — situație tensionată",
    type: "parent",
    urgency: "high",
    timeoutSeconds: 75,
    timeoutPenalty: 45,
    scenario: `Ora 13:00. Doamna Ionescu — mama Elenei — a venit neanunțată. Elena a luat 4 la ultimul test, deși mama e convinsă că fata știe materia perfect. Tonul doamnei e agresiv de la început: "Ați greșit la corectare!" Ai documentele de față, dar și o clasă care te așteaptă la 13:15.`,
    choices: [
      {
        id: "t3c1",
        text: "Îi explici calm și detaliat fiecare răspuns greșit al Elenei, cu dovezi.",
        xpReward: 80,
        skillEffects: { comunicare: 15, empatie: 8, organizare: 10 },
        immediateConsequence: "Mama se calmează. Recunoaște că Elena a mai zis că nu a pregătit tema.",
        longTermConsequence: "Elena vine la consultații. Nota crește la semestrul următor.",
        isOptimal: true,
      },
      {
        id: "t3c2",
        text: "Îi spui că nu poți discuta acum, programezi o întâlnire formală cu directoarea.",
        xpReward: 50,
        skillEffects: { organizare: 8, comunicare: -5, empatie: -8 },
        immediateConsequence: "Mama pleacă supărată. Zice că 'va rezolva altfel'.",
        longTermConsequence: "Plângere la Inspectorat. Audit al notelor tale. Stres ridicat.",
        isOptimal: false,
      },
      {
        id: "t3c3",
        text: "Oferi să refaci testul Elenei cu supraveghere strictă săptămâna viitoare.",
        xpReward: 65,
        skillEffects: { empatie: 10, rezilienta: 5, organizare: -5 },
        immediateConsequence: "Mama acceptă surprinsă. Tensiunea scade.",
        longTermConsequence: "Elena pică și retestul. Situația e mai clară acum, fără conflict.",
        isOptimal: false,
      },
    ],
  },
  {
    id: "t4",
    hour: 15,
    minute: 30,
    title: "Inspecția directoarei — lecție demonstrativă",
    type: "evaluation",
    urgency: "critical",
    timeoutSeconds: 45,
    timeoutPenalty: 70,
    scenario: `Ora 15:30. Directoarea intră fără să bată în ușă. Ai clasa a IX-a C — cea mai dificilă clasă. Trei elevi vorbesc. Planul tău de lecție e pe jumătate terminat. Pe tablă ai o diagramă incompletă. Directoarea se așează în spatele clasei și scoate un caiet de observații.`,
    choices: [
      {
        id: "t4c1",
        text: "Continui lecția ca și cum nu s-ar fi întâmplat nimic — nu schimbi nimic.",
        xpReward: 70,
        skillEffects: { rezilienta: 15, organizare: 5, comunicare: 5 },
        immediateConsequence: "Directoarea notează că ești natural și neafectat de presiune.",
        longTermConsequence: "Feedback pozitiv la raportul de inspecție. Recomandare pentru gradație.",
        isOptimal: true,
      },
      {
        id: "t4c2",
        text: "Îți schimbi complet abordarea — faci o lecție 'de show' improvizată.",
        xpReward: 45,
        skillEffects: { comunicare: 8, organizare: -10, rezilienta: 5 },
        immediateConsequence: "Lecția pare artificială. Directoarea observă că nu urmezi planul.",
        longTermConsequence: "Feedback mixt — creativitate da, consecvență nu.",
        isOptimal: false,
      },
      {
        id: "t4c3",
        text: "Implici directoarea — o inviti să interacționeze cu elevii ca 'invitat special'.",
        xpReward: 85,
        skillEffects: { comunicare: 18, empatie: 10, organizare: 5 },
        immediateConsequence: "Directoarea e plăcut surprinsă. Elevii sunt mai atenți.",
        longTermConsequence: "Lecție menționată ca 'exemplu de bune practici' la consiliul profesoral.",
        isOptimal: true,
      },
    ],
  },
  {
    id: "t5",
    hour: 17,
    minute: 0,
    title: "Sfârșitul zilei — raport și epuizare",
    type: "admin",
    urgency: "medium",
    timeoutSeconds: 120,
    timeoutPenalty: 20,
    scenario: `Ora 17:00. Toate orele s-au terminat. Trebuie să completezi catalogul electronic, să răspunzi la 12 emailuri de la părinți, să pregătești lecția de mâine și să corectezi 22 de lucrări. Partenerul/a ți-a trimis mesaj: 'Vii acasă la timp azi?' Ai energie pentru aproximativ 90 de minute de muncă eficientă.`,
    choices: [
      {
        id: "t5c1",
        text: "Faci totul — rămâi până la 20:00, sacrifici seara personală.",
        xpReward: 55,
        skillEffects: { organizare: 15, rezilienta: -10, empatie: -5 },
        immediateConsequence: "Tot e rezolvat, dar ești epuizat. Partenerul/a e dezamăgit/ă.",
        longTermConsequence: "Burnout în 3 luni. Eficiența ta scade vizibil.",
        isOptimal: false,
      },
      {
        id: "t5c2",
        text: "Prioritizezi: catalogul + 3 emailuri urgente, restul mâine dimineață.",
        xpReward: 85,
        skillEffects: { organizare: 10, rezilienta: 12, empatie: 8 },
        immediateConsequence: "Pleci la timp. Te simți vinovat dar echilibrat.",
        longTermConsequence: "Sustenabilitate pe termen lung. Ești mai odihnit și mai eficient.",
        isOptimal: true,
      },
      {
        id: "t5c3",
        text: "Nu faci nimic extra — pleci imediat, 'mâine e o zi nouă'.",
        xpReward: 15,
        skillEffects: { organizare: -15, rezilienta: 3, empatie: 2 },
        immediateConsequence: "Pleci relaxat, dar catalogul necompletat generează email de la director.",
        longTermConsequence: "Reputație de neseriozitate. Colegii se plâng.",
        isOptimal: false,
      },
    ],
  },
];

export const RANDOM_EVENTS: RandomEvent[] = [
  {
    id: "re1",
    triggerAfterTask: "t1",
    probability: 0.4,
    title: "Elev cu criză de anxietate",
    description: "Maria iese brusc din clasă plângând. Colega ei îți spune în șoaptă că Maria are probleme acasă.",
    effect: { empatie: 10, organizare: -5 },
    xpEffect: 30,
    notification: "⚠️ Situație sensibilă: Maria are nevoie de ajutor imediat.",
  },
  {
    id: "re2",
    triggerAfterTask: "t2",
    probability: 0.35,
    title: "Telefon de la Inspectorat",
    description: "Inspectorul școlar anunță o vizită neplănuită pentru după-amiază.",
    effect: { rezilienta: -8, organizare: 5 },
    xpEffect: -20,
    notification: "📞 URGENT: Inspectoratul vine astăzi. Pregătește dosarul de inspecție!",
  },
  {
    id: "re3",
    triggerAfterTask: "t3",
    probability: 0.3,
    title: "Elev care copiază la test",
    description: "Surprinzi un elev cu fița sub bancă în timp ce supraveghezi testul.",
    effect: { disciplina: 10, empatie: -5 },
    xpEffect: 25,
    notification: "🚨 Incident: Copiat la test detectat. Cum procedezi?",
  },
];

export const SCHEDULED_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "warning",
    message: "📅 Peste 15 minute ai întâlnirea cu mama Elenei. Pregătește-ți documentele!",
    triggerBeforeTaskId: "t3",
    minutesBefore: 15,
    autoHideSeconds: 8,
  },
  {
    id: "n2",
    type: "urgent",
    message: "🚨 URGENT: Conflictul dintre Radu și Victor escaladează în curte. Acționează acum!",
    triggerBeforeTaskId: "t2",
    minutesBefore: 0,
    autoHideSeconds: 5,
  },
  {
    id: "n3",
    type: "consequence",
    message: "📉 Ai ignorat elevul deranjator de la ora 8. Acum toată clasa e neatentă.",
    triggerBeforeTaskId: "t4",
    minutesBefore: 30,
    autoHideSeconds: 8,
  },
  {
    id: "n4",
    type: "warning",
    message: "⏰ Directoarea face inspecții astăzi. Fii pregătit/ă în orice moment.",
    triggerBeforeTaskId: "t4",
    minutesBefore: 60,
    autoHideSeconds: 6,
  },
  {
    id: "n5",
    type: "achievement",
    message: "🌟 Ai gestionat excelent conflictul! +15 Empatie, +12 Comunicare",
    triggerBeforeTaskId: "t3",
    minutesBefore: -5,
    autoHideSeconds: 6,
  },
];
